AirUTN/AirUTN/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponseRedirect

urlpatterns = [
    url(r'^$', lambda r: HttpResponseRedirect('bookings/')),
    url(r'^bookings/', include('bookings.urls')),
    url(r'^admin/', admin.site.urls)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AirUTN/bookings/urls.py
from django.conf.urls import url
from django.urls import re_path
from . import views

app_name = 'bookings'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^search/', views.hotel_search, name='hotel_search'),
    url(r'^property/([0-9]+)/$', views.hotel_details, name='hotel_details'),
    url(r'^check_availability/', views.check_availability, name='check_availability'),
    #url(r'^reservation/([0-9]+)/(?P<date>[0-9]{4}-?[0-9]{2}-?[0-9]{2})/(?P<date>[0-9]{4}-?[0-9]{2}-?[0-9]{2})/)$', views.successful_booking, name='successful_booking')
    re_path(r'^reservation/([0-9]+)/([0-9]+)/([0-9]+)/([0-9]+)/([0-9]+)/([0-9]+)/([0-9]+)$', views.successful_booking, name='successful_booking')
]

AirUTN/bookings/models.py
import os
from django.db import models
from django.contrib.auth.models import User

def property_image_rename(instance, filename):
    path = "hotels/images/"
    if instance.id is not None:
        name = str(instance.id) + filename
    elif not Property.objects.last():
        name = str(1) + filename
    else:
        name = str(Property.objects.latest('id').pk + 1) + filename
    return os.path.join(path, name)

class City(models.Model):
    name = models.CharField(blank=False, null=False, max_length=100)

    class Meta:
        verbose_name_plural = "cities"

    def __str__(self):
        return self.name

class Property(models.Model):
    name = models.CharField(blank=False, null=False, max_length=50, default="Name")
    description = models.TextField(blank=False, null=False, default="Description", max_length=100)
    picture = models.ImageField(blank=False, null=True, upload_to=property_image_rename)
    max_pax = models.PositiveIntegerField(blank=False, null=False, default=1)
    daily_cost = models.FloatField(blank=False, null=False, default=0)
    city = models.ForeignKey(City, on_delete=models.DO_NOTHING, null=True, blank=False)
    owner = models.ForeignKey(User, null=True, blank=True, on_delete=models.DO_NOTHING)

    class Meta:
        verbose_name_plural = "properties"

    def __str__(self):
        return self.name

class Reservation(models.Model):
    reservation_date = models.DateField(blank=False, null=False, auto_now=True)
    total_amount = models.FloatField(blank=True, null=True)
    first_name = models.CharField(blank=True, null=True, max_length=50)
    last_name = models.CharField(blank=True, null=True, max_length=50)
    email = models.EmailField(blank=True, null=True, max_length=200)
    property = models.ForeignKey(Property, on_delete=models.DO_NOTHING, blank=False, null=False)

    def __str__(self):
        return self.first_name + ' ' + self.last_name

class ReservationDate(models.Model):
    date = models.DateField(blank=False, null=False)
    property = models.ForeignKey(Property, on_delete=models.CASCADE, blank=False, null=True)
    reservation = models.ForeignKey(Reservation, on_delete=models.SET_NULL, blank=True, null=True)

def __str__(self):
    return self.property.name

AirUTN/bookings/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.http import HttpResponse, Http404

from .models import City, Property, ReservationDate, Reservation

from datetime import datetime, date


def index(request):
    cities = City.objects.all()
    context = {'cities': cities }
    return render(request, 'bookings/index.html', context)


def hotel_search(request):
    
    if request.method == 'GET':
        properties = Property.objects.all()        
        context = {'properties': properties}
        return render(request, 'bookings/hotel_search.html', context)
    if request.method == 'POST':
        city = request.POST.get('city', False)
        pax = request.POST.get('pax', False)
        datebegin = request.POST.get('depart', False)
        dateEnd = request.POST.get('return', False)
        properties = Property.objects.all()
        propertiesFiltered = []
        if not city.__eq__('None'):
            properties = properties.filter(city=city)

        if not pax.__eq__('None'):
            properties = properties.filter(max_pax__gte=pax)

        if not datebegin == '' and not dateEnd == '':
            diastotales = days_between(datebegin, dateEnd)
            for property in properties:
                reservation = ReservationDate.objects.all()
                reservation = reservation.filter(property=property,reservation__isnull=True)
                initialindex = get_reservation_index(datebegin,reservation)
                finalindex = get_reservation_index(dateEnd,reservation)
                if initialindex > -1 and finalindex > -1:
                    newreservation = reservation.filter()[initialindex:finalindex]
                    
                    if len(newreservation) == diastotales:
                        propertiesFiltered.append(property)    
                              

        context = {'properties': propertiesFiltered}
        return render(request, 'bookings/hotel_search.html', context)

def hotel_details(request, property_id):
    try:
        requested_property = Property.objects.get(id=property_id)
        service = requested_property.daily_cost * 0.08
    except Property.DoesNotExist as property_dont_exist :
        raise Http404("Not Found") from property_dont_exist
    return render(request, 'bookings/hotel-details.html', {'property': requested_property, 'service': service})

def days_between(d1, d2):
       d1 = datetime.strptime(d1, "%Y-%m-%d")
       d2 = datetime.strptime(d2, "%Y-%m-%d")
       return abs((d2 - d1).days)
     
def get_reservation_index(date,reservationDate):
    a = -1
    for i, e in enumerate(reservationDate):
        if str(e.date) == str(date):
            a = i
    return a  # for not found reservation date

def check_availability(request):
    if request.method == 'POST':
        datetime_start_date = datetime.strptime(request.POST['start_date'], '%Y-%m-%d').date()
        datetime_end_date = datetime.strptime(request.POST['end_date'], '%Y-%m-%d').date()
        requested_property = Property.objects.get(id=request.POST['property_id'])
        reservation_dates = ReservationDate.objects.filter(property=requested_property.id)
        for reservation_date in reservation_dates:
            if reservation_date.reservation is not None:
                if datetime_start_date <= reservation_date.date <= datetime_end_date:
                    return render(request, 'bookings/no-availability.html')        
        count = 0
        for reservation_date in reservation_dates:
            if datetime_start_date <= reservation_date.date <= datetime_end_date:
                r = Reservation(
                reservation_date=reservation_date,
                property=requested_property,
                first_name=request.POST['first_name'],
                last_name=request.POST['last_name'],
                email=request.POST['email'])
                r.save()
                reservation_date.reservation = r
                reservation_date.save()
                count = count + 1
        if count == 0:
            return render(request, 'bookings/no-availability.html')
        r.total_amount = r.property.daily_cost * r.property.reservationdate_set.filter(reservation=r).count() *1.08
        r.save()        
        return redirect('bookings:successful_booking', r.id,
        datetime_start_date.year,datetime_start_date.month,datetime_start_date.day,
        datetime_end_date.year,datetime_end_date.month,datetime_end_date.day)

def successful_booking(request, reservation_id,year1,month1,day1,year2,month2,day2):
    
    dateBegin = date(int(year1),int(month1),int(day1))
    dateEnd = date(int(year2),int(month2),int(day2))
    try:
        requested_reservation = Reservation.objects.get(id=reservation_id)
        reservationDates = list(ReservationDate.objects.all())        
        initialindex = get_reservation_index(dateBegin,reservationDates)
        finalindex = get_reservation_index(dateEnd,reservationDates)        
        reservationDates = reservationDates[initialindex:finalindex+1]
        
        dates = []
        for d in reservationDates:
            dates.append(d.date)        
        total = "{:.2f}".format(requested_reservation.total_amount)        
    except Property.DoesNotExist:
        raise Http404("Not Found")
    return render(request, 'bookings/itinerary.html', {'reservation': requested_reservation, 'reservation_dates': dates, 'total_amount': total })

AirUTN/bookings/templates/bookings/hotel-details.html
{% extends "./../layout/layout.html" %}

{% load static %}

{% block title %}Search Results{% endblock %}

{% block styles %}
{% endblock %}

{% block content %}

	{% include "./../layout/navbar.html" %}

	<div class="container">
		<div class="row">
			<div class="col-12 col-md-10 offset-md-1 pt-3 pb-3" style="background-color: #f5f5f5;">
				<div class="card bg-dark text-white">
					<img class="card-img" src="{{ property.picture.url }}" width="600" height="300" alt="Card image"
					     style="opacity: 0.5;">
					<div class="card-img-overlay">
						<h1 class="card-title">{{ property.name|title }}</h1>
						<p class="card-text small text-muted">{{ property.city.name|capfirst }}</p>
						<p class="card-text">{{ property.description|upper }}</p>
						<h2>AR$ {{ property.daily_cost }}</h2>
						<p>Commission per service AR$ %8 x Cost x days of reserve</p>
					</div>
				</div>
			</div>
			<div class="col-12 col-md-10 offset-md-1 pt-3 pb-3" style="background-color: #f5f5f5;">
				<form action="/bookings/check_availability/" method="post">
					{% csrf_token %}
                    <div class="form-row align-items-center">
                        <div class="form-group col-sm-3">
                            <label for="inputEmail4">First Name</label>
                            <input type="text" name="first_name" class="form-control mb-2 mb-sm-0" placeholder="Federico" required>
                        </div>
                        <div class="form-group col-sm-3">
                            <label for="inputEmail4">Last Name</label>
                            <input type="text" name="last_name" class="form-control" placeholder="Anastasi" required>
                        </div>
                        <div class="form-group col-sm-3">
                            <label for="inputEmail4">Email</label>
                            <input type="email" name="email" class="form-control" placeholder="yourmail@example.com" required>
                        </div>
                    </div>
					<div class="form-row align-items-center">
						<div class="form-group col-sm-3">
                            <label for="inputEmail4">Check-in</label>
							<input type="date" name="start_date" class="form-control mb-2 mb-sm-0" required>
						</div>
						<div class="form-group col-sm-3">
                            <label for="inputEmail4">Check-out</label>
							<input type="date" name="end_date" class="form-control" required>
						</div>
						<input type="hidden" name="property_id" value="{{ property.id }}">
					</div>
                    <div class="form-group float-right">
                        <button type="submit" class="btn text-white" style="background: #009BEB">Reserve</button>
                    </div>
				</form>
			</div>
		</div>
	</div>

	{% include "./../layout/footer.html" %}

{% endblock %}

{% block scripts %}{% endblock %}

AirUTN/bookings/templates/bookings/hotel_search.html
{% extends "./../layout/layout.html" %} 
{% load static %} 
{% block title %}Search Results {% endblock %} 
{% block styles %} {% endblock %} 
{% block content %} 
{% include "./../layout/navbar.html" %}

<div class="container">
  <div class="card-deck">
    <div class="card-group card-columns ">
      <div class="row">
        <div class="col-12">
          {% if properties %} {% for property in properties %}
          <div class="card border-info mb-3 " style="width: 18rem">
            <img class="card-img-top" style="width: 18rem; height: 10rem;" src="{{ property.picture.url }}" width="100%" height="100%" alt="Card image cap"/>
            <div class="card-body">
              <h5 class="card-title" >{{ property.name|title }}</h5>
              <p class="card-text">{{ property.description }}</p>
              <p class="card-text">
                <small class="text-muted">{{ property.city.name|capfirst }}</small>
              </p>
              <div class="float-right" style="padding-bottom: 10px;">
                {% url 'bookings:hotel_details' property.id as hotel_details %}
                <a class="btn text-white" style="background: #009BEB" href="{{ hotel_details }}" role="button">Reserve</a>
              </div>
              <div class="col-12">
                <div class="float-right">
                  <h5 style="padding-right: 20px"> AR$&nbsp;{{ property.daily_cost }}</h5>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
          	<h6 class="text-center">No more results</h6>
          {% else %}
          	<h6 class="text-center"> Couldn't find properties, try again later. </h6>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>

{% include "./../layout/footer.html" %} 
{% endblock %}

AirUTN/bookings/templates/bookings/index.html
{% extends "./../layout/layout.html" %}
{% load static %}
{% block title%}Home{% endblock %} 
{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}" />
{% endblock %} {% block content %} {% include "./../layout/navbar.html" %}

<link
  href="https://fonts.googleapis.com/css?family=Poppins:300,400,500"
  rel="stylesheet"
/>

<div class="s002">
  <form action="/bookings/search/" method="post">
    {% csrf_token %}
      <legend>Search Hotels</legend>
    <div class="inner-form">
      <div class="input-field fouth-wrap">
        <div class="icon-wrap">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
          >
            <path
              d="M12 2C8.13 2 5 5.13 5 9c0 5.25 7 13 7 13s7-7.75 7-13c0-3.87-3.13-7-7-7zm0 9.5c-1.38 0-2.5-1.12-2.5-2.5s1.12-2.5 2.5-2.5 2.5 1.12 2.5 2.5-1.12 2.5-2.5 2.5z"
            ></path>
          </svg>
        </div>
        <select data-trigger="" name="city" id="city">
                  <option value="{{ None }}" >Select a city</option>
                  {% for city in cities %}
										<option value="{{ city.id }}">{{ city.name }}</option>
									{% endfor %}
        </select>
      </div>
      <div class="input-field second-wrap">
        <div class="icon-wrap">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
          >
            <path d="M17 12h-5v5h5v-5zM16 1v2H8V1H6v2H5c-1.11 0-1.99.9-1.99 2L3 19c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2h-1V1h-2zm3 18H5V8h14v11z"></path>
          </svg>
        </div>
        <input
          class="datepicker"
          id="depart"
          name="depart"
          type="text"
          placeholder="29 Aug 2018"/>
      </div>
      <div class="input-field third-wrap">
        <div class="icon-wrap">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
          >
            <path
              d="M17 12h-5v5h5v-5zM16 1v2H8V1H6v2H5c-1.11 0-1.99.9-1.99 2L3 19c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2h-1V1h-2zm3 18H5V8h14v11z"
            ></path>
          </svg>
        </div>
        <input
          class="datepicker"
          id="return"
          name="return"
          type="text"
          placeholder="30 Aug 2018"
        />
      </div>
      <div class="input-field fouth-wrap">
        <div class="icon-wrap">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
          >
            <path
              d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z"
            ></path>
          </svg>
        </div>
        <select data-trigger="" name="pax" id="pax">
        <option value="{{ None }}" >Passangers</option>
          <option value="1"> 1 Pax</option>
          <option value="2" >2 Pax</option>
          <option value="3" >3 Pax</option>
          <option value="4" >4 Pax</option>
        </select>
      </div>
      <div class="input-field fifth-wrap">
        <button class="btn-search" type="submit">SEARCH</button>
      </div>
    </div>
  </form>

  <script src="{% static 'js/extention/choices.js' %}"></script>
  <script src="{%static 'js/extention/flatpickr.js' %}"></script>
  <script>
    flatpickr(".datepicker", {});
  </script>
  <script>
    const choices = new Choices("[data-trigger]", {
      searchEnabled: false,
      itemSelectText: "",
    });
  </script>

  {% include "./../layout/footer.html" %} {% endblock %}
</div>

AirUTN/bookings/templates/bookings/itinerary.html
{% extends "./../layout/layout.html" %}

{% load static %}

{% block title %}Search Results{% endblock %}

{% block styles %}
{% endblock %}

{% block content %}

    {% include "./../layout/navbar.html" %}

    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="alert alert-light" role="alert">
                    <h6 class="text-center">Successful booking at Air UTN.</h6>
                </div>
            </div>
            <div class="col-12">
                <h6>Hi, this is the itinerary for <span class="text-info">{{ reservation.first_name }} {{ reservation.last_name }}</span>!:</h6>
                <br>
                <p class="font-weight-bold">Email: <span class="text-info">{{ reservation.email }}</span></p>
                <p class="font-weight-bold">Total : $<span class="text-info">{{ total_amount }}</span></p>
                <p class="font-weight-bold">Reservation made on: <span class="text-info">{% now "Y-m-d" %} </span></p>
                <p class="font-weight-bold">Your reservation days are : </p>
                {% for date in reservation_dates  %}
                    <span class="text-info">*{{ date }}</span><br>
                {% endfor %}
            </div>
        </div>
    </div>

    {% include "./../layout/footer.html" %}

{% endblock %}

{% block scripts %}{% endblock %}

AirUTN/bookings/templates/bookings/no-availability.html
{% extends "./../layout/layout.html" %}

{% load static %}

{% block title %}Search Results{% endblock %}

{% block styles %}
{% endblock %}

{% block content %}

	{% include "./../layout/navbar.html" %}

	<div class="container">
		<div class="row">
			<div class="col-12">
                <div class="alert alert-danger" role="alert">
                    <h6 class="text-center">This property is not available this date.</h6>
                </div>
                {% url 'bookings:index' as index %}
                <a type="button" href="{{ index }}" class="btn btn-secondary btn-lg btn-block">Go to search</a>
			</div>
		</div>
	</div>

	{% include "./../layout/footer.html" %}

{% endblock %}

{% block scripts %}{% endblock %}

AirUTN/bookings/templates/layout/footer.html
<footer class="footer">
	<div class="container">
		<span class="text-muted">



		</span>
	</div>
</footer>

AirUTN/bookings/templates/layout/layout.html
{% load static %}
<!doctype html>

<html lang="en">

<head>
	<title>AirUTN - {% block title %}Layout{% endblock %}</title>

	<link rel="icon"
	      type="image/png"
	      href="{% static 'logo.png' %}"/>

	<!-- Required meta tags -->
	<meta charset="utf-8">

	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap-4.5.3-dist/css/bootstrap.min.css' %}"/>

	<!-- Optional JavaScript -->
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
	        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
	        crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"
	        integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh"
	        crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"
	        integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ"
	        crossorigin="anonymous"></script>

	<link rel="stylesheet" type="text/css" href="{% static 'css/sticky-footer.css' %}"/>

	<link rel="stylesheet" type="text/css" href="{% static 'animate-css/animate.css' %}"/>

						  <link rel="stylesheet" href="{% static 'css/main.css' %}" />

	{% block styles %}{% endblock %}

</head>

<body>

<div id="content" style="background-image: url('https://www.toptal.com/designers/subtlepatterns/patterns/hotel-wallpaper.png');">
	{% block content %}{% endblock %}
</div>

{% block scripts %}{% endblock %}

</body>

</html>

AirUTN/bookings/templates/layout/navbar.html
{% load static %}
<nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
	{% url 'bookings:index' as index %}
	<a class="navbar-brand" href="{{ index }}">
		 <img src="{% static 'images/logo.png' %}" width="30" height="30" class="d-inline-block align-top"
		     alt="logo"/>
		Air UTN
	</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
	        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto">

		</ul>
		<ul class="navbar-nav">
			<li class="nav-item">
				<a class="nav-link active" href="{{ index }}">Hotels <span class="sr-only">(current)</span></a>
			</li>
		</ul>
	</div>
</nav>